package com.demo.common.model;

import com.demo.common.model.base.BaseMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Member extends BaseMember<Member> {
	public static final Member dao = new Member().dao();
}
